### ISSUE TITLE
server hooks

### ISSUE THREAD

**Issue by jakubknejzlik** [alxarch/express-git#2]
I've been trying to create server post/pre-receive and update hooks, but they don't get executed (and no "remote:" messages are shown). Do you have any idea why this could be happening? I've tried pushover with same settings and everything worked.

**Comment by alxarch** [comment]
Please try the latest (0.7) version which uses an `EventEmitter` interface for hooks. i.e:

``` js
expressGit.on("update", function (repository, change) {
  // change is an {before, after, ref} object
});
```
